version: '3'
services:
  worker:
    build:
      context: ./worker
    environment:
      NODE_ENV: development
      DB_HOST: mariadb
    ports:
      - 80:80
    links:
      - mariadb
    volumes:
      - ./worker/index.js:/usr/src/app/index.js
  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
