version: '3'
services:
  loader:
    build:
      context: ./loader
    environment:
      NODE_ENV: development
      DB_HOST: mariadb
    links:
      - mariadb
    volumes:
      - ./loader/index.js:/usr/src/app/index.js
      - ./loader/lib:/usr/src/app/lib
  worker:
    build:
      context: ./worker
    environment:
      NODE_ENV: development
      DB_HOST: mariadb
    links:
      - mariadb
    volumes:
      - ./worker/index.js:/usr/src/app/index.js
      - ./sample_src:/video_src
      - ./sample_dest:/video_dest
  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: default_database
