version: '3'
services:
  loader:
    build:
      context: ./loader
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
      DB_HOST: mysql
    ports:
      - 80:80
    links:
      - mysql
    volumes:
      - ./loader/index.js:/usr/src/app/index.js
      - ./loader/lib:/usr/src/app/lib
      - ./loader/routes:/usr/src/app/routes
  worker:
    build:
      context: ./worker
    environment:
      NODE_ENV: development
      DB_HOST: mysql
    links:
      - mysql
    volumes:
      - ./worker/index.js:/usr/src/app/index.js
      - ./sample_src:/video_src
      - ./sample_dest:/video_dest
  mysql:
    image: percona:5
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: default_database
